pulsarVersion=3.2.4
bookieVersion=4.16.7
bookieCount=2
managedLedgerDefaultEnsembleSize=2
managedLedgerDefaultWriteQuorum=1
managedLedgerDefaultAckQuorum=1
bookieDistribution=/home/stephen/github/java/bookkeeper/dev/entrylog-corruption-855/pulsar-ldpreload-4.16.7-bookie-cluster/runtime/downloads/bookkeeper-server-4.16.7-bin.tar.gz
bookieServerJar=/home/stephen/github/java/bookkeeper/dev/entrylog-corruption-855/pulsar-ldpreload-4.16.7-bookie-cluster/runtime/bookkeeper/bookkeeper-server-4.16.7/lib/org.apache.bookkeeper-bookkeeper-server-4.16.7.jar
failpointClassAbsent=org/apache/bookkeeper/bookie/DefaultEntryLogger$BufferedLogChannel$PartialFlushFault.class
ldPreloadFaultSource=/home/stephen/github/java/bookkeeper/dev/entrylog-corruption-855/tools/ldpreload-entrylog-fault/entrylog_fault.c
ldPreloadFaultLib=/home/stephen/github/java/bookkeeper/dev/entrylog-corruption-855/pulsar-ldpreload-4.16.7-bookie-cluster/runtime/fault/libbk_entrylog_fault.so
