#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export ROUNDS="${ROUNDS:-5}"
export RUN_ID="${RUN_ID:-single-replica-$(date +%Y%m%d-%H%M%S)}"
export BOOKIE_COUNT="${BOOKIE_COUNT:-2}"
export MANAGED_LEDGER_DEFAULT_ENSEMBLE_SIZE="${MANAGED_LEDGER_DEFAULT_ENSEMBLE_SIZE:-2}"
export MANAGED_LEDGER_DEFAULT_WRITE_QUORUM="${MANAGED_LEDGER_DEFAULT_WRITE_QUORUM:-1}"
export MANAGED_LEDGER_DEFAULT_ACK_QUORUM="${MANAGED_LEDGER_DEFAULT_ACK_QUORUM:-1}"
export BK_ENTRYLOG_FAULT_MIN_WRITE_BYTES="${BK_ENTRYLOG_FAULT_MIN_WRITE_BYTES:-65536}"
export BK_ENTRYLOG_FAULT_EXACT_WRITE_BYTES="${BK_ENTRYLOG_FAULT_EXACT_WRITE_BYTES:-65536}"

export BK_ENTRYLOG_FAULT_AFTER_MATCHES_1="${BK_ENTRYLOG_FAULT_AFTER_MATCHES_1:-1}"
export BK_ENTRYLOG_FAULT_AFTER_MATCHES_2="${BK_ENTRYLOG_FAULT_AFTER_MATCHES_2:-2}"
export BK_ENTRYLOG_FAULT_AFTER_MATCHES_3="${BK_ENTRYLOG_FAULT_AFTER_MATCHES_3:-3}"
export BK_ENTRYLOG_FAULT_AFTER_MATCHES_4="${BK_ENTRYLOG_FAULT_AFTER_MATCHES_4:-4}"
export BK_ENTRYLOG_FAULT_AFTER_MATCHES_5="${BK_ENTRYLOG_FAULT_AFTER_MATCHES_5:-5}"

exec "${SCRIPT_DIR}/run-stability.sh"
